name: Empty CHANGELOG.md

on: 
  release:
    types: [published]

jobs:
  empty-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.repository.default_branch }}
        
    - name: Empty CHANGELOG.md
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "github-actions"
        
        if [ -s CHANGELOG.md ]; then
          echo "Comitting emptied CHANGELOG.md"
        else
          echo "CHANGELOG.md is already empty. skipping comitting"
          exit 0
        fi

        rm CHANGELOG.md
        touch CHANGELOG.md

        git add CHANGELOG.md
        git commit -m "Empty CHANGELOG.md"
        git push