name: Empty CHANGELOG.md

on:
  release:
    types: [published]

jobs:
  empty-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0

      - name: Empty CHANGELOG.md
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"

          rm CHANGELOG.md
          touch CHANGELOG.md

          git add CHANGELOG.md
          git commit --allow-empty -m "Empty CHANGELOG.md after v$(git describe --tags --abbrev=0)"
          git push
