name: Webpack

on: 
  push:
    branches:
    - main

jobs:
  webpack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}

    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm run build
    - run: |
        cd "$GITHUB_ACTION_PATH"

        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"

        git pull
        git add -f dist
        git commit -m "Compile Webpack"
        git push