name: Webpack Test

on: [pull_request, push]

jobs:
  webpack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.repository.full_name }}
          ref: ${{ github.head_ref }}

      - name: Get commit SHA
        run: echo "LATEST_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "15"

      - name: Test-Build Webpack
        run: |
          npm install
          npm run build
          echo "Beta-${{ env.LATEST_SHA }}" > dist/VERSION
        env:
          DRIBBBLISH_VERSION: Beta
          COMMIT_HASH: ${{ env.LATEST_SHA	}}

      - name: Push to beta-release branch
        if: github.event_name == 'push'
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release-beta
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: DribbblishDynamic_vBeta-${{ env.LATEST_SHA	}}
          path: dist/**
